### ISSUE TITLE
Нет кнопки вернуться на главную

### ISSUE THREAD

**Issue by DmitryArhipov** [Yekaterinburg-Tree-Map/ekbtrees-frontend#41]
Не нашёл кнопку "Вернуться на главную" при переходе на карту или на "Вход". Надо добавить эту кнопку, чтобы пользователь всегда мог вернуться на главную страницу

**Comment by vvadik** [comment]
Всегда можно перейти на главную страницу если нажмешь на логотип слева сверху, кажется это всем известная кнопка "вернуться на главную"
